GET http://localhost:4000/api/blogs/

###
POST http://localhost:4000/api/blogs/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbWFudGhhQDIzIiwiaWQiOiI2MmYxYmU1NjRkZmNjYWY1YTBiYTZlNWYiLCJpYXQiOjE2NjAxNTA2MzcsImV4cCI6MTY2MDE1NDIzN30.FsvPCkP-eWGezOVSkOi_x2OuNx79OMIBbxHhD_gzFw8

{
    "title" : "Mern",
    "likes" : 54,
    "url": "webdev.com",
    "author" : "Samantha",
    "userId": "62f1be564dfccaf5a0ba6e5f"
}

###
POST http://localhost:4000/api/users/
content-type: application/json

{
    "name" : "Samantha",
    "username" : "samantha@23",
    "password" : "0980"
}

###
POST http://localhost:4000/api/login/
content-type: application/json

{
    "username" : "samantha@23",
    "password" : "0980"
}



###
GET  http://localhost:4000/api/users/


