GET http://localhost:4000/api/blogs/

###
POST http://localhost:4000/api/blogs/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthc3VtaUAyMyIsImlkIjoiNjJmNWM2YjgxNWEyOWYyMzA5OGJiZWIzIiwiaWF0IjoxNjYwMzk3OTUwLCJleHAiOjE2NjA0MDE1NTB9.hURO9HdzkhbBEiFS1jc3nmYUp1pYQZ75jqswaNgyZrw

{
    "title" : "Info system",
    "likes" : 47,
    "url": "info.com",
    "author" : "Kasumi",
}

###
POST http://localhost:4000/api/users/
content-type: application/json

{
    "name" : "Kasumi",
    "username" : "kasumi@23",
    "password" : "1234"
}

###
POST http://localhost:4000/api/login/
content-type: application/json

{
    "username" : "kasumi@23",
    "password" : "1234"
}



###
GET  http://localhost:4000/api/users/


