GET http://localhost:4000/api/blogs/

###
POST http://localhost:4000/api/blogs/
content-type: application/json

{
    "title" : "Linux",
    "likes" : 96,
    "url": "brand.com",
    "author" : "Hari Bahadur",
    "userId": "62ea2a1f65849cf6e7aeaa72"
}

###
POST http://localhost:4000/api/users/
content-type: application/json

{
    "name" : "Mona",
    "username" : "mona@23",
    "password" : "0000"
}